### ISSUE TITLE
Pre-built binaries?

### ISSUE THREAD

**Issue by KoolenDasheppi** [nettlep/magic#5]
I think it would be a good idea to provide some pre-built binaries for people who don't have a Mac. I do have a Mac, but it's old and I can't even fit Xcode on the amount of space I have left. I'm gonna try a macOS VM in a few minutes, but it'd still be nice to have the binaries. Especially for Abra, packaged as an IPA file.

**Comment by nettlep** [comment]
I'm actively working on getting Abra into the App Store. They're being fickle though and have rejected the app. I'll keep trying.

Before I post a binary release of any other tools for macOS, I'd like to find a way to build them as universal binaries. I haven't found a way yet, given that they require a couple third-party libraries from Homebrew which are not available as universal libraries.

**Comment by nettlep** [comment]
Universal binaries for Steve & Cardbars have been archived as a release.

In addition, Abra for iOS is currently in review with Apple. Abra for macOS will be going into review soon.

**Comment by nettlep** [comment]
In attempting to publish Abra for macOS through the App Store, I was forced to work through and resolve the last remaining build issues related to third-party dependencies and universal builds. This is good news, because it also resolved those issues for Steve and Cardbars.

To that end, I've created another release with pre-built binaries for Steve and CardBars that have those dependency issues fixed.

The new release is here: https://github.com/nettlep/magic/releases/tag/v1.0-fixed-deps

**Comment by dlbroadfoot** [comment]
Thanks for publishing the binaries for Steve and Cardbars!

Would it be possible to also include a prebuilt binary for Whisper to run on Raspberry Pi?

**Comment by nettlep** [comment]
Hey @dlbroadfoot - your Raspberry Pi binary has arrived:

https://github.com/nettlep/magic/discussions/7

I'd be curious to hear if/how this works for you. Please use the discussion to follow up with questions/issues.
